import React from 'react';
import {useNotifications} from '../../contexts/NotificationContext';

const scheduledFacilityReports = [
  {
    name: 'Daily census export',
    cadence: 'Every day · 6:00 AM',
    recipients: 'ops@taylorfacility.com',
    lastRun: 'Today · 05:58 AM',
  },
  {
    name: 'Medication administration audit',
    cadence: 'Mondays · 5:30 AM',
    recipients: 'pharmacy@taylorfacility.com',
    lastRun: 'Sep 18 · 05:31 AM',
  },
  {
    name: 'Life safety checks',
    cadence: 'Fridays · 4:00 PM',
    recipients: 'facilities@taylorfacility.com',
    lastRun: 'Sep 15 · 04:02 PM',
  },
];

const safetyChecklist = [
  {item: 'Fire suppression inspection', status: 'Completed · Sep 12'},
  {item: 'Generator load test', status: 'Scheduled · Sep 21'},
  {item: 'Nurse call calibration', status: 'In progress'},
];

const recentFacilityExports = [
  {name: 'Room readiness log', format: 'CSV', generated: 'Today · 07:10 AM'},
  {name: 'Therapy attendance roster', format: 'PDF', generated: 'Yesterday · 03:55 PM'},
];

function FacilityReportsView() {
  const {addNotification} = useNotifications();

  const handleRunNow = () => {
    addNotification('Facility census export is running. You will receive a notification when complete.', {
      type: 'success',
    });
  };

  return (
    <div className="hub-view hub-view--facility-reports">
      <section className="hub-section">
        <header className="hub-section__header">
          <h2>Scheduled facility reports</h2>
          <p>Ensure agency teams receive timely operational updates.</p>
        </header>
        <table className="hub-table">
          <thead>
            <tr>
              <th scope="col">Report</th>
              <th scope="col">Cadence</th>
              <th scope="col">Recipients</th>
              <th scope="col">Last run</th>
            </tr>
          </thead>
          <tbody>
            {scheduledFacilityReports.map((report) => (
              <tr key={report.name}>
                <th scope="row">{report.name}</th>
                <td>{report.cadence}</td>
                <td>{report.recipients}</td>
                <td>{report.lastRun}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section className="hub-section hub-section--split">
        <article className="hub-card hub-card--table">
          <header className="hub-card__header">
            <div>
              <h3>Safety checklist</h3>
              <p>Track environmental and clinical safety requirements.</p>
            </div>
          </header>
          <table className="hub-table">
            <thead>
              <tr>
                <th scope="col">Item</th>
                <th scope="col">Status</th>
              </tr>
            </thead>
            <tbody>
              {safetyChecklist.map((item) => (
                <tr key={item.item}>
                  <th scope="row">{item.item}</th>
                  <td>{item.status}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </article>
        <aside className="hub-card hub-card--table">
          <header className="hub-card__header">
            <div>
              <h3>Recent exports</h3>
              <p>Manual reports generated by facility administrators.</p>
            </div>
          </header>
          <table className="hub-table">
            <thead>
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Format</th>
                <th scope="col">Generated</th>
              </tr>
            </thead>
            <tbody>
              {recentFacilityExports.map((exportItem) => (
                <tr key={exportItem.name}>
                  <th scope="row">{exportItem.name}</th>
                  <td>{exportItem.format}</td>
                  <td>{exportItem.generated}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </aside>
      </section>

      <section className="hub-section">
        <div className="hub-card hub-card--actions">
          <div>
            <h3>Run census export now</h3>
            <p>Generate an on-demand census file to share with agency partners.</p>
          </div>
          <button
            type="button"
            className="hub-card__action hub-card__action--primary"
            onClick={handleRunNow}
          >
            Run export
          </button>
        </div>
      </section>
    </div>
  );
}

export default FacilityReportsView;
